class Array
  # If +number+ is greater than the size of the array, the method
  # will simply return the array itself sorted randomly
  def randomly_pick(number)
    sort_by{ rand }.slice(0...number)
  end
end

module SampleText

lorem_ipsum = <<END
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vehicula luctus dolor, et auctor dui tempus vel. Sed diam diam, interdum eu convallis sit amet, sollicitudin sed purus. Nullam ultricies neque vitae velit sodales nec consectetur leo accumsan. Sed eget mi eros. Suspendisse vestibulum ligula in est adipiscing non sollicitudin ligula tempor. Nulla nec magna a massa lobortis pretium nec at dui. In in ante odio, et molestie mauris. Integer nisl sapien, congue quis accumsan sed, rhoncus et justo. Suspendisse sit amet ligula justo. Donec viverra dui sed elit sagittis placerat. Suspendisse vitae mauris justo. Cras ac arcu eget dui ultrices fermentum. Praesent euismod nulla in magna ultricies nec eleifend libero porta. Phasellus et iaculis libero. Praesent ac libero ante. Duis sodales massa nec risus mattis sagittis. Fusce at sem mauris. In augue lacus, faucibus sit amet accumsan at, malesuada ac sapien. Vivamus mauris diam, vehicula non blandit non, accumsan nec nisl.
Mauris sagittis, libero eu mattis blandit, nisl lacus adipiscing dolor, in fermentum odio mi vel tortor. Suspendisse lectus sapien, venenatis nec tristique aliquam, tristique blandit tellus. Vivamus eget nunc neque. Vestibulum eu velit turpis, ac consequat neque. Maecenas nec justo at augue tempor facilisis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque semper auctor mi ut pellentesque. Donec eget leo vel dui tempor consequat. Nunc vehicula justo accumsan nunc scelerisque vel porta erat euismod. Phasellus eleifend metus sit amet sapien mattis cursus. Sed auctor accumsan volutpat. Nulla luctus, neque eu vestibulum condimentum, felis dolor viverra justo, sit amet posuere leo neque a purus. Aenean lacinia lectus ac sapien semper imperdiet.
Quisque semper purus vitae nunc pharetra convallis. Nunc sed est nisl. Donec luctus est tempus mauris imperdiet lacinia. Morbi lacus nunc, commodo in vestibulum in, placerat pulvinar massa. In est turpis, congue sodales hendrerit id, convallis aliquet leo. Donec imperdiet, sem id tristique dignissim, lectus neque ullamcorper tellus, at volutpat sem odio ac mi. Nullam id mattis nibh. Cras ut bibendum nibh. Quisque sed lacus dui. Cras congue euismod justo in vehicula. Sed in mauris ac neque fringilla luctus. Praesent commodo dignissim risus ac tempus. Integer eleifend pulvinar mi, quis interdum nisl volutpat sit amet. Etiam auctor, nisl ac condimentum mattis, velit risus commodo tortor, in consectetur ipsum sem eu sem. In lorem risus, bibendum id imperdiet in, tincidunt et felis. Quisque elementum, urna nec pellentesque commodo, turpis nibh viverra lorem, vel posuere orci urna vel mauris. Etiam congue egestas nisi eget iaculis.
Aenean eu dolor erat, laoreet dignissim diam. Etiam vitae molestie mauris. Sed fringilla diam sed augue vulputate ullamcorper. Aenean eget eros non metus mattis malesuada eu in est. Fusce et mauris lacus, vitae pharetra neque. Nulla vitae diam sed augue eleifend gravida. Ut tellus orci, posuere id vestibulum at, egestas nec sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egestas, nisl in accumsan sagittis, augue neque tincidunt odio, ac pulvinar mauris mauris vel dui. Cras sed metus dolor, non suscipit justo. Quisque non purus nisi. Ut varius, libero in tincidunt convallis, lorem velit posuere dui, quis sagittis mi magna ac mauris.
Integer tincidunt nulla a dui porttitor lacinia. Nullam non erat eros. Nunc purus nulla, sagittis sed mattis vel, varius vel ipsum. Vivamus pharetra nunc eget libero viverra scelerisque. Donec consequat rutrum tortor, in commodo lectus sodales sit amet. Maecenas id eros diam, nec sagittis ipsum. Vivamus non turpis a magna tincidunt egestas id ac lorem. In ut neque vitae dolor ultricies tristique quis sed nisl. Etiam adipiscing sem diam, vitae consequat nisl. Curabitur elit sapien, dignissim scelerisque fermentum ac, cursus at metus. Vivamus posuere diam non nulla interdum eget eleifend risus faucibus. Mauris commodo enim et urna lobortis at tempor nisl iaculis. Duis vel sollicitudin ipsum. Aenean sed dictum lacus. Morbi molestie risus eu turpis venenatis feugiat. Fusce vestibulum fermentum mollis.
In at aliquam ligula. Curabitur semper dapibus laoreet. In in convallis sapien. Morbi molestie consectetur arcu at tincidunt. Donec tincidunt luctus erat nec varius. Aliquam erat volutpat. Sed eu nisi eu nisi dictum porta ac vel nisl. Nulla sed convallis ante. Suspendisse nulla sapien, rutrum vitae bibendum eu, commodo id mauris. Proin aliquet, lacus in porttitor porttitor, diam mi blandit purus, id tempor urna odio vel turpis. Vestibulum fringilla pulvinar dolor non viverra. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Donec blandit tincidunt libero vitae gravida. Mauris feugiat velit metus. Duis varius augue nec purus tristique pulvinar. Donec a erat ligula. Mauris egestas diam eget ipsum luctus ultricies. Donec et ante leo. Suspendisse nec tellus at risus imperdiet iaculis mattis vitae nisi. Sed sit amet magna eget orci vestibulum auctor sit amet sit amet metus. Curabitur quis metus nunc, at sagittis purus. Quisque vitae eros orci. Vivamus vulputate vehicula luctus.
Integer vestibulum, purus a ullamcorper laoreet, turpis risus euismod mauris, eget tincidunt mi velit eu mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer massa dui, pellentesque eu dictum sed, scelerisque ut augue. Suspendisse pretium placerat diam, at consequat felis tempor id. Donec pharetra fermentum diam, sed pretium ligula pellentesque id. Quisque vehicula, libero id vulputate egestas, massa libero pharetra elit, vitae viverra lectus neque eu tellus. Mauris placerat laoreet massa, sed adipiscing nulla sodales a. In hac habitasse platea dictumst. Aenean aliquam erat in metus blandit non condimentum nisi suscipit. Sed iaculis ullamcorper metus at vulputate. In cursus nunc nec eros porttitor auctor. Ut sit amet risus massa. Etiam lacus purus, placerat vel vehicula et, dapibus at nisi. Maecenas nec enim ligula, ut mattis odio. Vestibulum id interdum risus. Maecenas vel lorem sit amet elit malesuada gravida. Curabitur eros nunc, viverra a porttitor ac, lobortis a ligula. Praesent felis lorem, feugiat vel porta eget, mollis vel nisi.
Nam vitae risus eu mi laoreet malesuada. Curabitur ligula metus, rutrum id pharetra at, molestie id purus. Aliquam mattis, nisl sed iaculis ultrices, libero elit porta nisl, ac molestie nunc ligula eget arcu. Nulla vulputate justo vel elit rutrum vel varius nibh lobortis. Etiam et velit nec urna bibendum venenatis. Integer sed facilisis ipsum. Donec nulla nisl, sagittis et viverra vitae, consectetur ut ligula. Proin tincidunt, nulla a lacinia pretium, eros leo volutpat lacus, ac vestibulum massa orci ut sapien. Pellentesque a urna malesuada libero volutpat aliquet. Proin nibh leo, porttitor nec tristique vitae, rutrum at libero. Nunc pulvinar erat tellus. Proin augue turpis, dictum eu aliquet porta, posuere ut tortor. Curabitur eu ligula ut elit pellentesque iaculis nec ornare lorem.
Cras pharetra, ante non bibendum aliquet, mi lorem fringilla turpis, vestibulum pulvinar lacus lectus bibendum sapien. Integer fringilla pellentesque purus, sed luctus quam interdum sit amet. Vivamus luctus dapibus eros, ut pulvinar ante pulvinar a. Curabitur lobortis mollis neque, eget semper dolor pellentesque et. Maecenas viverra laoreet lacus sed interdum. Aliquam euismod dapibus quam, at iaculis ipsum tempus et. Vivamus tempus sem lacinia enim convallis luctus. In vestibulum mattis massa a placerat. Curabitur et diam vitae nulla congue elementum eget sagittis magna. Praesent suscipit tristique nunc non vestibulum. Sed a tortor felis, eget viverra dolor. Sed felis risus, blandit ut convallis et, dictum quis dui. Sed venenatis orci quis purus tincidunt sollicitudin. Mauris eros quam, mollis id congue vel, tempus a mi.
Aenean pellentesque condimentum pulvinar. Maecenas laoreet odio ac elit tincidunt feugiat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi et placerat purus. Quisque eu odio nisl. Nunc nec mi ac nunc condimentum facilisis in non odio. Sed quam est, euismod eu auctor vitae, volutpat nec mi. Cras sed arcu in turpis cursus malesuada. Integer magna elit, euismod eu placerat id, fermentum id justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris at viverra lorem. In eget quam ut est mollis porta in at dui. Aenean euismod diam urna, et ullamcorper sapien. In iaculis ligula ac enim lobortis porttitor. Cras at facilisis lectus. Vestibulum faucibus, tellus porta semper mollis, est felis consequat justo, ac volutpat sem tortor facilisis lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus ut faucibus justo. Quisque dignissim quam et libero facilisis at lacinia odio suscipit. Nam mollis urna eu mauris consequat at ultricies erat hendrerit.
Praesent et lorem dolor, sed laoreet metus. Mauris sit amet quam laoreet neque pellentesque vehicula. Nulla facilisi. Proin molestie, nunc sed suscipit fringilla, turpis ipsum fermentum neque, vel pretium tortor tellus a nunc. Fusce eu erat feugiat tellus bibendum aliquet. Duis nec euismod lacus. Nullam placerat, magna eget placerat aliquam, eros erat porta leo, vel mollis mauris eros non dolor. Integer ornare, nunc scelerisque pulvinar fringilla, metus lacus tristique sem, interdum commodo ipsum sem eget augue. Proin eu lacus a diam volutpat congue ac ut eros. Aenean molestie sapien vitae nibh commodo eu rhoncus orci egestas. Vestibulum tincidunt luctus porttitor.
Vestibulum posuere purus ut lacus euismod interdum. Nam et orci vitae lorem laoreet aliquam. Donec et arcu a nisl dignissim molestie eu non ante. Quisque justo tortor, placerat ut hendrerit sit amet, adipiscing in ante. Mauris ipsum ante, blandit vel suscipit ac, sagittis at turpis. Maecenas ac metus dui. Mauris convallis sagittis interdum. Phasellus scelerisque tellus vehicula elit dictum tincidunt. Integer pharetra, ante quis gravida interdum, eros sapien egestas augue, eu adipiscing mi urna ut turpis. Mauris sed.
END
  LOREM_IPSUM = lorem_ipsum.split(/.\n|\. /).uniq
end
